package co.edu.uniquindio.poo.model;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false)
public class Administrador extends Usuario{
    private final String correo = "admin@unieventos.com";
    private final String contrasena = "admin123";

    private static Administrador instancia;
    
    // Manually define the constructor that was previously generated by @AllArgsConstructor
    public Administrador(String id, String nombre, String telefono, String correo) {
        super(id, nombre, telefono, correo);
    }
    
    // Adjusted no-argument constructor to avoid conflict
    public Administrador() {
        super("1234", "nombre", "32133231", "admin@unieventos.com");
    }

    public static Administrador obtenerInstancia() {
        
        if (instancia == null) {
            instancia = new Administrador();
        }
        
        return instancia;
    }

    @Override
    public void displayUserInfo() {
        System.out.println("Cliente: " + getCorreo() + ", nombre: " + getContrasena());
        
    }
}